#ifndef HEADERS_FUNCTIONS_ARM9_H_
#define HEADERS_FUNCTIONS_ARM9_H_
void _start(void);
void FunctionStub_02000b98(void);
void FunctionStub_0200120c(void);
void FunctionStub_02001eb4(void);
void FunctionStub_02001ecc(void);
void FunctionStub_0200372c(void);
void FunctionStub_0200396c(void);
void FunctionStub_02003984(void);
void FunctionStub_02007ca8(void);
void FunctionStub_02007cc0(void);
void FunctionStub_02008ed8(void);
void FunctionStub_0200d414(void);
void FunctionStub_02010448(void);
void InitializeBattlePokemonFields(struct battle_combatants *param_1);
void BattleSetUnkField0x0(struct battle_combatants *param_1,int *param_2);
void BattleSetCurrentHp(struct battle_combatants *param_1,int8_t param_2);
void BattleSetStylerLevel(struct battle_combatants *param_1,int8_t param_2);
void BattleSetPartnerAssistUnlockStatus(struct battle_combatants *param_1,int param_2);
void GetPartnerGaugeCurrent(struct battle_combatants *param_1,int param_2);
void BattleGetPartnerGaugeMax(struct battle_combatants *param_1,int param_2);
void BattleSetPartnerGaugeFillRate(struct battle_combatants *param_1,int param_2);
void BattleAddPartyPokemon(struct battle_combatants *param_1,int16_t form_id,int8_t param_3);
void BattleTryAddNewEnemyForm(struct battle_combatants *param_1,uint param_2,uint param_3);
void BattleSetArenaGraphicId(struct battle_combatants *param_1,int8_t param_2);
void BattleSetWeatherEffectId(struct battle_combatants *param_1,int8_t param_2);
void BattleSetSequenceScriptId(struct battle_combatants *param_1,int8_t param_2);
void BattleSetTutorialScriptId(struct battle_combatants *param_1,int8_t param_2);
void BattleSetStartScriptId(struct battle_combatants *param_1,int8_t param_2);
void BattleSetBGMId(struct battle_combatants *param_1,int8_t param_2);
void BattleSetViewPartyStatus(struct battle_combatants *param_1,int param_2);
void BattleSetCanFleeStatus(struct battle_combatants *param_1,int param_2);
void BattleSetBossFightStatus(struct battle_combatants *param_1,int param_2);
void BattleSetUnkField0x52(struct battle_combatants *param_1,int8_t param_2);
void BattleSetUnkField0x54(struct battle_combatants *param_1,int8_t param_2);
void BattleSetGenderAndUniform(struct battle_combatants *param_1,int16_t param_2);
int * BattleGetUnkField0x0(struct battle_combatants *param_1);
int8_t BattleGetCurrentHp(struct battle_combatants *param_1);
int8_t BattleGetStylerLevel(struct battle_combatants *param_1);
bool BattleCanPartnerUsePokeAssist(struct battle_combatants *param_1);
int BattleGetPartnerGaugeCurrent(struct battle_combatants *param_1);
int BattleGetPartnerGaugeFillRate(struct battle_combatants *param_1);
int8_t BattleGetNumEnemyForms(struct battle_combatants *param_1);
int16_t BattleGetEnemyFormId(struct battle_combatants *param_1,int param_2);
int8_t BattleGetEnemyCount(struct battle_combatants *param_1);
int8_t BattleGetUnkEnemyData0x41(struct battle_combatants *param_1,int param_2);
int8_t BattleGetPartyPokemonCount(struct battle_combatants *param_1);
int16_t BattleGetPartyFormIds(struct battle_combatants *param_1,int param_2);
int8_t BattleGetPokeAssistDataById(struct battle_combatants *param_1,int param_2);
int8_t BattleGetArenaGraphicId(struct battle_combatants *param_1);
int8_t BattleGetSequenceScriptId(struct battle_combatants *param_1);
int8_t BattleGetTutorialScriptId(struct battle_combatants *param_1);
int8_t BattleGetStartScriptId(struct battle_combatants *param_1);
int8_t BattleGetBGMId(struct battle_combatants *param_1);
bool BattleGetViewPartyStatus(struct battle_combatants *param_1);
bool BattleGetCanFleeStatus(struct battle_combatants *param_1);
bool BattleGetBossFightStatus(struct battle_combatants *param_1);
int8_t BattleGetUnkField0x52(struct battle_combatants *param_1);
int8_t BattleGetFieldAllocBits(struct battle_combatants *param_1);
int8_t BattleGetUnkField0x54(struct battle_combatants *param_1);
int16_t BattleGetGenderAndUniform(struct battle_combatants *param_1);
void FunctionStub_02010cec(void);
void ZeroQuestBody(struct quest* param_1);
void ZeroQuestFooter(struct quest* param_1);
void FunctionStub_020117ac(void);
void zero_pokemon_data(struct pokemon_data* param_1);
void FunctionStub_02015108(void);
void FunctionStub_02015120(void);
pokemon_data * RetrievePokemonByFormId(struct ranger_data *param_1,int form_id);
void MaybeHandleStylerLevelUp(struct ranger_data *param_1,uint styler_level);
void UpdatePlayTime(struct ranger_data* param_1);
void DebugPrint(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void AssignPartnerMoods(struct ranger_data* param_1);
uint GetStylerUpgradeById(struct ranger_data *param_1,int param_2);
void SetPlayerExp(struct ranger_data* param_1, uint32_t param_2);
int32_t AddPlayerExp(struct ranger_data* param_1, int32_t param_2);
void SetMaxStepsRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddMaxStepsRecord(struct ranger_data* param_1, int32_t param_2);
void SetconversationsRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddconversationsRecord(struct ranger_data* param_1, int32_t param_2);
void SetTargetsCheckedRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddTargetsCheckedRecord(struct ranger_data* param_1, int32_t param_2);
void SetGameSavesRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddGameSavesRecord(struct ranger_data* param_1, int32_t param_2);
void SetPokemonRidesRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddPokemonRidesRecord(struct ranger_data* param_1, int32_t param_2);
void SetPartnerPokemonBestnessIfGreaterByIndex(struct ranger_data *param_1,int param_2,uint param_3);
int32_t IncrementPartnerPokeAssistsBySpecies(struct ranger_data *param_1,int16_t param_2,int param_3);
undefined2 MaybeGetBestPartnerRecord(struct ranger_data *param_1);
void SetCaptureLineLenRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddCaptureLineLenRecord(struct ranger_data* param_1, int32_t param_2);
void SetNumLoopsRecord(struct ranger_data* param_1, uint32_t param_2);
int32_t AddNumLoopsRecord(struct ranger_data* param_1, int32_t param_2);
void SetPokemonCapturedRecord(struct ranger_data* param_1, int16_t param_2);
int16_t AddPokemonCapturedRecord(struct ranger_data* param_1, int16_t param_2);
void SetFledPokemonRecord(struct ranger_data* param_1, int16_t param_2);
int16_t AddFledPokemonRecord(struct ranger_data* param_1, int16_t pokemon_fled);
void SetPokeAssistsUsedRecord(struct ranger_data* param_1, int16_t param_2);
int16_t AddPokeAssistsUsedRecord(struct ranger_data* param_1, int16_t param_2);
void ZeroSettingsAndVariables(struct settings_and_variables* param_1);
void ZeroEventVariables(struct settings_and_variables* param_1);
void SetEventVariable(struct settings_and_variables* param_1, int32_t param_2, int32_t param_3);
int32_t GetEventVariable(struct settings_and_variables* param_1, int32_t param_2);
void ZeroQuestVariables(struct settings_and_variables* param_1);
void SetQuestVariable(struct settings_and_variables* param_1, int32_t param_2, int32_t param_3);
int32_t GetQuestVariable(struct settings_and_variables* param_1, int32_t param_2);
void SetSettingsVariable(struct settings_and_variables* param_1, int32_t param_2, int32_t param_3);
int32_t GetSettingsVariable(struct settings_and_variables* param_1, int32_t param_2);
void FunctionStub_0201a40c(void);
void FunctionStub_020222c8(void);
void FunctionStub_020222d4(void);
void FunctionStub_02022710(void);
void FunctionStub_020228c0(void);
void FunctionStub_020237e0(void);
void FunctionStub_02029778(void);
void FunctionStub_0202a5f8(void);
void FunctionStub_0202d394(void);
void DebugPrintError(char* string);
undefined4 CopyStringToRangerDebugBuffer(char** param_1);
undefined4 BattleSetBGMIdSafe(undefined4 *param_1);
undefined4 BattleSetUnkField0x49Safe(undefined4 *param_1);
undefined4 BattleDisableFleeing(void);
undefined4 BattleSetUnkField0x54Safe(undefined4 *param_1);
undefined4 BattleSetUnkField0x4bSafe(undefined4 *param_1);
undefined4 BattleSetUnkField0x4cSafe(undefined4 *param_1);
undefined4 BattleSetUnkField0x4dSafe(undefined4 *param_1);
undefined4 BattleSetStylerLevelSafe(undefined4 *param_1);
undefined4 BattleAddPartyPokemonSafe(undefined4 *param_1);
int8_t GetRangerStylerRank(void);
int32_t GetRangerStylerType(void);
undefined GetStylerLevelSafe(void);
int8_t GetRangerMaxHpSafe(void);
int8_t GetRangerCurrentHpSafe(void);
undefined4 EnableSlotStatusBit2(pokemon_data *param_1);
undefined4 DisableSlotStatusBit2(pokemon_data *param_1);
undefined4 EnableSlotStatusBit1(pokemon_data *param_1);
undefined4 DisableSlotStatusBit1(pokemon_data *param_1);
undefined4 BitorPartnerPokemonStatus(uint32_t* param_1);
uint32_t BitandPartnerPokemonStatus(uint32_t* param_1);
int8_t GetPartnerPokemonMood(int32_t* param_1);
void FunctionStub_02032a44(void);
void FunctionStub_0203365c(void);
void DisableActiveTimersAndMore(void);
void InitTimerType1(int32_t* param_1);
void InitTimerType2(int32_t* param_1);
void SetTimerTypeNone(void);
undefined4 SetTimerType1(void);
undefined4 SetTimerType2(void);
int32_t GetTimer1Duration(void);
undefined4 SetTimer1Duration(int32_t* param_1);
undefined4 TimerIsActive(void);
undefined4 IncrementPokemonRidesRecord(void);
int32_t GetGameSavesRecordSafe(void);
undefined4 GetPartnerIndexFromFormID(int16_t param_1);
void FunctionStub_020358fc(void);
void FunctionStub_02035fe4(void);
void FunctionStub_0203e930(void);
void FunctionStub_0204078c(void);
void FunctionStub_0204129c(void);
void FunctionStub_02041920(void);
void FunctionStub_02043124(void);
void FunctionStub_02043128(void);
void FunctionStub_020439c4(void);
void FunctionStub_020439c8(void);
void FunctionStub_02044144(void);
void FunctionStub_02044148(void);
void FunctionStub_020441ac(void);
void DebugPrintInternal(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void DebugPrintInternalVeneer(undefined4 param_1, undefined4 param_2, undefined4 param_3, undefined4 param_4);
void FunctionStub_02046d3c(void);
int32_t close(int32_t fd);
int32_t socket(int32_t domain, int32_t family, int32_t protocol);
int32_t bind(int32_t sockfd, const struct sockaddr_in* addr);
int32_t connect(int32_t sockfd, const struct sockaddr_in* addr);
int32_t recv(int32_t sockfd, void* buf, size_t size, int32_t flags);
int32_t recvfrom(int32_t sockfd, void* buf, size_t size, int32_t flags, struct sockaddr_in* addr, int32_t addr_len);
int32_t send(int32_t sockfd, const void* buf, size_t size, int32_t flags);
int32_t sendto(int32_t sockfd, void* buf, size_t size, int32_t flags, undefined* addr, int32_t addr_len);
int32_t CloseVeneer(int32_t fd);
void FunctionStub_02049d08(void);
void FunctionStub_0206129c(void);
void GX_Init(void);
void GX_InitGxState(void);
void OS_InitIrqTable(void);
void OS_SetIrqFunction(uint32_t intr_bit, os_irq_function function);
uint32_t OS_SetIrqMask(uint32_t mask);
uint32_t OS_EnableIrqMask(uint32_t mask);
uint32_t OS_DisableIrqMask(uint32_t mask);
uint32_t OS_ResetRequestIrqMask(uint32_t mask);
void OS_SetIrqStackChecker(void);
void OS_InitLock(void);
int32_t OS_LockByWord(uint16_t lock_id, struct os_lock_word* lockp, lock_ctrl_funcp ctrl_funcp);
int32_t OS_UnlockByWord(uint16_t lock_id, struct os_lock_word* lockp, lock_ctrl_funcp ctrl_funcp);
int32_t OS_UnlockCartridge(uint16_t lock_id);
int32_t OS_UnlockCartridgeVeneer(uint16_t lock_id);
int32_t OS_GetLockID(void);
void OSi_InsertLinkToQueue(struct os_thread_queue* queue, struct thread* thread);
void OSi_InsertThreadToList(struct thread* thread);
void OS_RescheduleThread(void);
void OS_InitThread(void);
void OS_SleepThread(struct os_thread_queue* queue);
void OS_WakeupThreadDirect(struct thread* thread);
os_switch_thread_callback OS_SetSwitchThreadCallback(os_switch_thread_callback callback);
void OSi_IdleThreadProc(void* arg);
void OS_SetThreadDestructor(struct thread* thread, int32_t value);
bool OS_SaveContext(struct os_context* context);
void OS_LoadContext(struct os_context* context);
void OS_InitMutex(struct os_mutex* mutex);
void DC_FlushAll(void);
void DC_InvalidateRange(void* start_addr, uint32_t n_bytes);
void DC_FlushRange(void* data, uint32_t size);
void OSi_WaitVCount0(void);
void OS_Init(void);
void OS_InitArena(void);
void OS_InitArenaEx(void);
void* OS_GetInitArenaLo(enum os_arena_id id);
void OS_SetArenaHi(enum os_arena_id id, void* new_hi);
void OS_SetArenaLo(enum os_arena_id id, void* new_lo);
void OS_SetProtectionRegion1(uint32_t param);
void OS_SetProtectionRegion2(uint32_t param);
void OS_InitException(void);
void OSi_ExceptionHandler(void);
void OS_InitVAlarm(void);
int32_t OS_DisableInterrupts(void);
int32_t OS_RestoreInterrupts(int32_t new_value);
void OS_InitReset(void);
void OS_GetMacAddress(uint8_t* macAddress);
void OS_GetOwnerInfo(struct user_settings* settings);
uint32_t Math_CountLeadingZeros(uint32_t x);
void OSi_InitVramExclusive(void);
void OS_Panic(void);
void OS_Halt(void);
void MI_SetWramBank(enum mi_wram cnt);
void MI_DmaCopy16(uint32_t dma_no, void* src, void* dest, uint32_t size);
void MI_StopDma(uint32_t dma_no);
void MIi_CheckDma0SourceAddress(uint32_t dma_no, uint32_t src, uint32_t size, uint32_t dir);
void MIi_CpuClear16(uint16_t val, void* ptr, int32_t len);
void MIi_CpuCopy16(void* src, void* dest, int32_t len);
void MIi_CpuClear32(uint32_t val, void* ptr, int32_t len);
void MIi_CpuCopy32(void* src, void* dest, int32_t len);
void MIi_CpuClearFast(uint32_t val, void* ptr, int32_t len);
void MIi_CpuCopyFast(void* src, void* dest, int32_t len);
void MI_CpuFill8(void* ptr, char val, uint32_t len);
void MI_CpuCopy8(void* src, void* dest, uint32_t n);
void MI_Init(void);
void Pxi_Init(void);
void Pxi_InitFifo(void);
void Pxi_SetFifoRecvCallback(int32_t fifo_tag, pxi_fifo_callback callback);
void Pxi_IsCallbackReady(int32_t fifo_tag, enum pxi_proc proc);
int32_t Pxi_SendWordByFifo(int32_t fifo_tag, uint32_t data, bool err);
void Pxii_HandlerRecvFifoNotEmpty(void);
void PMi_CallCallbackAndUnlock(void);
void PM_Init(void);
void PMi_CommonCallback(void);
uint32_t PM_ForceToPowerOff(void);
void Cardi_InitCommon(void);
void Card_Enable(bool enable);
bool Cardi_ReadFromCache(struct card_rom_stat* p);
void Cardi_SetRomOp(uint32_t cmd1, uint32_t cmd2);
void Cardi_ReadCard(struct card_rom_stat* p);
void Card_Init(void);
void Cardi_OnFifoRecv(enum pxi_fifo_tag tag, uint32_t data, bool err);
void Cardi_TaskThread(void* arg);
void Card_InitPulledOutCallback(void);
void FunctionStub_0207484c(void);
void Ctrdgi_InitCommon(void);
void Ctrdgi_ChangeLatestAccessCycle(struct ctrdg_rom_cycle* r);
void Ctrdgi_RestoreAccessCycle(struct ctrdg_rom_cycle* r);
void Ctrdgi_LockByProcessor(uint16_t lock_id, struct ctrdg_lock_by_proc* info);
void Ctrdgi_UnlockByProcessor(uint16_t lock_id, struct ctrdg_lock_by_proc* info);
void Ctrdgi_SendtoPxi(uint32_t data);
void Ctrdg_Init(void);
int32_t abs(int32_t x);
void FunctionStub_020794d4(void);
int32_t mbtowc(wchar_t* pwc, const char* s, size_t n);
bool TryAssignByte(uint8_t* ptr, uint8_t val);
bool TryAssignByteWrapper(uint8_t* ptr, uint8_t val);
size_t wcstombs(char* dest, const wchar_t* src, size_t n);
void* memcpy(void* dest, const void* src, size_t n);
void* memmove(void* dest, const void* src, size_t n);
size_t strlen(const char* s);
char* strcpy(char* dest, const char* src);
char* strncpy(char* dest, const char* src, size_t n);
char* strcat(char* dest, const char* src);
int32_t strcmp(const char* s1, const char* s2);
int32_t strncmp(const char* s1, const char* s2, size_t n);
char* strchr(const char* string, int32_t c);
char* strstr(const char* haystack, const char* needle);
void FunctionStub_0207f910(void);
void FunctionStub_0207f9c0(void);
double _dadd(double a, double b);
unsigned long long _ll_ufrom_d(double d);
double _dmul(double a, double b);
double _drsub(double b, double a);
double _dsub(double a, double b);
float _fadd(float a, float b);
bool _dls(double a, double b);
bool _deq(double a, double b);
bool _fls(float a, float b);
float _frdiv(float divisor, float dividend);
float _fdiv(float dividend, float divisor);
int32_t _ffix(float f);
float _fflt(int32_t i);
float _fmul(float a, float b);
float _fsub(float a, float b);
long long _ll_mod(long long dividend, long long divisor);
long long _ll_sdiv(long long dividend, long long divisor);
unsigned long long _ll_udiv(unsigned long long dividend, unsigned long long divisor);
unsigned long long _ull_mod(unsigned long long dividend, unsigned long long divisor);
long long _ll_mul(long long a, long long b);
unsigned long long _s32_div_f(int dividend, int divisor);
unsigned long long _u32_div_f(uint32_t dividend, uint32_t divisor);
unsigned long long _u32_div_not_0_f(uint32_t dividend, uint32_t divisor);
void FunctionStub_02081c00(void);
void FunctionStub_02082e20(void);
void FunctionStub_02083544(void);
#endif